<script lang="ts">
  import { setCrumb } from '$lib/ui/crumb.svelte';
  $effect(() => {
    setCrumb([{ label: 'About', href: '/about/how' }, { label: 'How it is made' }]);
    return () => setCrumb([]);
  });
</script>

<svelte:head>
  <title>How Cultifolio is made</title>
  <meta name="description" content="Where every number on a species page comes from, how the habitat climate envelope and the map marker are worked out, what two fixed rules read from the curves, and what the app refuses to guess." />
</svelte:head>

<div class="kick" style="margin-top: 22px">About</div>
<h1 class="q">How it is made</h1>
<p class="secsub">Every figure on a species page has a source and a method. This page is the method. The rule underneath all of it: a number the app cannot derive is left out and said to be missing, never filled in.</p>

<nav class="seg topseg" aria-label="About"><a class="on" href="/about/how">How it is made</a><a href="/about/formats">Formats</a></nav>

<article class="prose">
  <h2 id="sources">What comes from where</h2>
  <p>A species page is assembled from public sources, each named on the page where its data appears, with the licence it came under. The name and its synonyms, family and order come from the <b>GBIF Backbone Taxonomy</b>; a name the backbone holds as a synonym is followed to the species it accepts (and an accepted subspecies or variety one step further, to its species), and the page says which name was asked for. The native range comes from the <b>World Checklist of Vascular Plants</b> at Kew, read from Kew's files; a name WCVP lists more than once (a homonym) is told apart by authorship, and when authorship does not decide, the page says the name is unresolved and attaches no range. Regions where WCVP records the plant as extinct are shown labelled as such and are never part of the range records are tested against. Where WCVP has no entry the app falls back to national checklists and says so, at country level only. Kew's own one-line descriptions of a species, its life form and climate class, are quoted on the page and credited to WCVP, RBG Kew; nothing is derived from them. Occurrence records come from <b>GBIF</b>. Monthly climate normals come from <b>CHELSA V2.1</b> (1981–2010, 30 arc-second), packed to a 0.05° grid: day and night temperature, rainfall, solar radiation, relative humidity, vapour-pressure deficit and wind. Elevation comes from <b>ETOPO 2022</b> on the same grid. Daily temperature extremes come from <b>NASA POWER</b> (1981 onward). Photographs come from <b>iNaturalist</b> research-grade observations and <b>Wikimedia Commons</b>, restricted to CC0, CC BY and CC BY-SA, and each carries its author and licence. The summary paragraph is <b>Wikipedia</b>'s, kept visibly separate and credited. Recent literature comes from <b>OpenAlex</b>.</p>
  <p>Nothing on a species page is written by a person or a language model. The cultivation sheet and the "In short" paragraph are figures with their sources and the readings two fixed rules make of them, and each row says which figure it rests on. No row says what a plant does, wants or tolerates, or what to do to it.</p>

  <h2 id="refusal">A refusal is not an absence</h2>
  <p>Sources rate-limit, time out and go down. When one does, the page says "not checked" for that section rather than showing an empty list, because "we could not ask" and "there is nothing" are different facts and a grower reading the page needs to know which. The corpus build keeps what a source gave last time when it refuses this time, and records the date it was carried from. What is carried is exact: literature, the summary and photographs, each per source, so a refused iNaturalist does not discard this build's Commons photographs; and the range, the records, the map marker and the climate as one snapshot when the occurrence or distribution source refuses, never piecemeal, because a range from one build and records from another would be a page no build made. The same rule applies in the other direction: a species with no habitat climate on file gets no derived climate rows, and a hybrid gets none at all, since it has no habitat.</p>

  <h2 id="records">Which records count</h2>
  <p>A species' records on GBIF include herbarium sheets with rounded coordinates, garden plants, and specimens filed under the wrong country. The app takes every georeferenced record with no flagged geospatial issue, drops living specimens (something somebody planted) and records marked introduced or managed, and tests each against the native range from WCVP, discarding records outside it. The range has to be WCVP's, with native status stated: a national checklist that only reports a plant present in a country cannot tell a wild record from a garden one, so for a name WCVP does not carry the page shows the records on a map, says the range is unverified, and derives no marker, no climate and no sheet from them. Restricted-licence records (CC BY-NC) inform the marker and the climate like any other; only openly licensed records are published on the map, in the data, or as the marker itself. Three agreeing records are enough for a narrow endemic; under a dozen the page says the evidence is thin.</p>

  <h2 id="marker">The map marker</h2>
  <p>The marker on the map is where the records are densest, and it decides nothing else. Records are binned at 1°, and the bin with most neighbours wins if it holds at least half the records or twice the runner-up; if no bin dominates at 1° the test repeats at 2° and 4°, and the densest 4° block stands when none dominates even there. Inside the winning cluster the densest 1° population is found again, and the marker is the openly licensed record nearest its middle, so the pin is somewhere the plant has been seen. When no openly licensed record lies in the population, the marker is the centre of the nearest tenth-of-a-degree cell instead, so that a restricted record's coordinates are never published; the page says which kind of point it is. The climate is not read at the marker.</p>

  <h2 id="climate">The climate envelope</h2>
  <p>The habitat climate is read across every in-range record, not at one point. Each record placed to within 10 km (or with no stated uncertainty; the vaguer ones stay on the map and off the climate) names one 0.05° cell of the packed CHELSA grid, and each distinct cell is read once, so a site visited a hundred times is one cell of climate and not a hundred votes. A cell at sea or on ice, where the grid has no land climate, is dropped and counted. Three land cells are the minimum; fewer, and the page says so and derives nothing. For each month and each variable the app takes the median across those cells, which is the year the sheet reads, and the 10th and 90th percentiles, which are the span the species is recorded in; the climate table prints both, and the page states how many cells and records the envelope rests on. Radiation is CHELSA's daily-mean shortwave flux, taken to a daily total by the 86,400 seconds in a day and converted to a daily light integral (PAR taken as 45% of shortwave at 4.6 µmol per joule, so 1 MJ/m²/day ≈ 2.07 mol/m²/day), because that is the unit a grower can compare with a window or a lamp.</p>
  <p>Extremes need daily data, which CHELSA does not give, and one series, so they are read at one cell: the typical cell, the one whose coldest night of the year is nearest the median coldest night across the envelope. The app fetches the NASA POWER daily series for that cell's 0.5° POWER cell and reduces it: the absolute minimum, the 1st-percentile night, the 99th-percentile day, and frost nights per year over the whole record. POWER's cell elevation and the grid cell's ETOPO elevation differ, so the series is lapse-corrected at 6.5 °C per 1,000 m of the difference, and the page says by how much; when the grid cell's mean elevation is below sea level (a coastal cell averaged with sea floor) no correction is applied, and the page says that instead. A series is used only if it covers twenty years at 95% completeness.</p>

  <h2 id="year">What the rules read</h2>
  <p>Two fixed rules read the median year, and the sheet labels every sentence they produce as a reading. The rain rule: the wet season is the smallest set of months that carries 70% of the year's rain; a wet season cooler than the year's mean is called a winter growing season, warmer a summer one. Eight or more wet months is no season. A temperature curve that moves less than 4 °C between its warmest and coldest month is flat, and then the rule infers no growing season even from a sharp rainy season; the page says the rain is sharp and that nothing is inferred from it, which is a different statement from "no season". Under 120 mm a year there is no rainy season to read at all, and the temperature rule names the cooler six months instead. A season that falls in two runs of months is printed as two runs. None of this says when the plant grows.</p>
  <p>Wherever habitat months are printed the page names the hemisphere they belong to and gives them shifted six months for a collection in the other one, because a Namaqualand plant whose rain falls in May to August has that season in a northern greenhouse from November to February, and the difference is the whole point. The label line and the sheet format a season through one function, so they cannot disagree.</p>

  <h2 id="floor">The cold floor</h2>
  <p>The floor on a sheet names the quantity it is: the 1st-percentile night at the typical cell from NASA POWER, or, when no extremes are on file, the coldest month's mean night in the median year from CHELSA, named as such. Where the archetype table has a conventional minimum for the plant's group and that figure is higher, the floor is the table's figure, and the same sentence says so and gives both numbers. It is a figure about a place, not a tested survival limit for a plant in a pot, and the page says so.</p>

  <h2 id="archetypes">Archetypes</h2>
  <p>The app keeps a small table of care archetypes (cactus or succulent, bulb or caudex, tropical foliage, orchid, epiphyte, fern, carnivore, temperate) resolved species → genus → family, and the page says which archetype and why it was chosen. The table supplies one figure, the conventional group minimum above, and no prose. Where a family splits between archetypes and the genus is not on the table, the app guesses nothing.</p>

  <h2 id="notes">The note in short</h2>
  <p>The paragraph at the top of the cultivation section is the sheet's rows in one-sentence form: each row is written with its own short form by the same rule at the same moment, and the note is those sentences in card order and nothing else. There is no second rule that could disagree with a card. It lists the rows each sentence came from. It is not written by a person or a model, and the page says so.</p>
  <p>The same discipline holds on a plant's own page, where its habitat figures sit beside the bench it lives on: for each compared figure the page shows the habitat median with its 10th–90th span and the bench's setting side by side, and gives no verdict, because the sky over a habitat and a climate percentile are facts about places, not measured tolerances of a plant in a pot. The papers listed on a species page are works whose title or abstract names the species, most cited first; they are a pointer to the literature, and nothing on the page is drawn from them.</p>

  <h2 id="collection">Your collection</h2>
  <p>Everything you record lives in your browser's storage on your device as an append-only log of field-level changes, each stamped with a hybrid logical clock. State is a fold over the log; two devices merge by taking the union of their logs, and for each field the latest change wins. That one rule is what backup restore, the v2 import and sync all use, which is why restoring an old backup over a newer collection loses nothing and why a sync interrupted halfway simply resumes. Sync encrypts every batch on the device with a key only you hold; the server stores ciphertext and cannot read a plant name. The <a href="/about/formats">formats page</a> has the details.</p>

  <h2 id="privacy">What the site knows about you</h2>
  <p>There are no accounts, no analytics and no tracking. Species pages are served from a static corpus; your collection never leaves your device unless you turn on sync, and then it leaves encrypted. Your browser does talk to two outside hosts, and you should know which: photographs on species pages load from iNaturalist's image host (inaturalist-open-data.s3.amazonaws.com) and Wikimedia Commons (upload.wikimedia.org), which see your address like any image host; and the species picker sends the name you are typing to this site's own <code>/api/names</code>, which asks api.gbif.org from the server, so that host sees the server's address and not yours. The frost watch asks MET Norway and, in the US, the National Weather Service from the server, never from your browser.</p>

  <h2 id="source">The source</h2>
  <p>Cultifolio is open source: the app under AGPL-3.0, the corpus tooling under MIT. Everything described on this page can be checked, run and rebuilt from <a href="https://github.com/zomethingje-eng/cultifolio">github.com/zomethingje-eng/cultifolio</a>, including the scripts that build a species corpus from the sources above. Problems and corrections are welcome there.</p>
</article>

<style>
  .prose { max-width: 720px; font-size: 15px; line-height: 1.6; color: var(--ink); font-family: var(--ui); }
  .prose h2 { font-family: var(--serif); font-size: 22px; margin: 28px 0 8px; }
  .prose p { margin: 0 0 12px; }
  .topseg { margin: 14px 0 6px; }
</style>
