<script lang="ts">
  import { setCrumb } from '$lib/ui/crumb.svelte';
  import PageHead from '$lib/ui/PageHead.svelte';
  $effect(() => {
    setCrumb([{ label: 'About', href: '/about/how' }, { label: 'Formats' }]);
    return () => setCrumb([]);
  });
</script>

<svelte:head>
  <title>Cultifolio formats</title>
  <meta name="description" content="The backup file, the change log, and the sync wire format, documented so you can read your own data without the app." />
</svelte:head>

<PageHead title="Formats" kick="About" places={false} sub="Your data is readable without this app: the change log, the backup file, and what sync puts on the server, all plain." />

<nav class="seg topseg" aria-label="About"><a href="/about/how">How it is made</a><a class="on" href="/about/formats">Formats</a></nav>

<article class="prose">
  <h2 id="log">The change log</h2>
  <p>A collection is a list of changes. Each change sets one field of one record:</p>
<pre><code>{`{ "t": "1789520000000-0001-ab12cd", "kind": "accession", "id": "2026-0001", "field": "notes", "value": "sulked all summer" }`}</code></pre>
  <p><code>t</code> is a hybrid logical clock: 13-digit millisecond wall time, a hex counter of four digits (up to six, only when a millisecond holds more than 65,535 changes), and the id of the device that made the change. It orders by wall time, then counter value, then device. A device follows a peer's clock only up to five minutes ahead of its own, so one phone set to the wrong year cannot become every device's clock. <code>kind</code> is one of <code>accession</code>, <code>event</code>, <code>location</code>, <code>sowing</code>, <code>photo</code>, <code>taxon</code>, <code>setting</code>. A delete is a change setting <code>_deleted</code> to true; a later change to any other field of that record revives it. The fields <code>id</code>, <code>kind</code> and <code>_t</code> belong to the record and cannot be set by a change (nor can the names <code>*</code> and <code>_deleted=</code>).</p>
  <p>To read a collection, sort the changes by <code>t</code> and apply them in order, keeping for each record and field the value with the greatest <code>t</code>. The result is the same whatever order the changes arrived in, and applying a change twice changes nothing. This is the whole merge rule; backup restore, the v2 import and sync all use it.</p>
  <p>Record shapes are plain JSON with flat fields. Records are keyed by an opaque identity (<code>id</code>, minted once on the device that made the record); the number a plant is known by is a field, <code>acc</code>, unique among live and dead plants and never reused, so two devices that mint the same number offline end up with two plants, one of them renumbered and told so, never one plant made of both. Records from before this separation used the number as the id; readers take <code>acc</code> when present and the id otherwise. Sowings carry their batch number in <code>no</code> the same way. An accession (a plant) has <code>taxonName</code>, <code>taxonKey</code> (GBIF), <code>cultivar</code>, <code>nameKind</code> (species, cultivar or hybrid), <code>parentage</code>, <code>fieldNumber</code>, <code>provenance</code> (wild, f1, fn, veg, unknown), <code>status</code>, <code>locationId</code>, <code>acquired</code>, <code>sourceFrom</code>, <code>sourceForm</code>, <code>price</code>, <code>notes</code>, <code>sowingId</code>, <code>cover</code>. An event has <code>acc</code>, <code>d</code> (YYYY-MM-DD), <code>t</code> (water, feed, repot, measure, treat, flower, move, note, death, audit, germinate, potup, loss…), and <code>note</code>, <code>used</code>, <code>cause</code>, <code>measures</code>, <code>n</code> as the type needs. A photo record holds <code>acc</code> or <code>sowing</code>, <code>d</code>, <code>dFrom</code> (exif or added), <code>caption</code>, <code>w</code>, <code>h</code>, <code>bytes</code>, <code>sha</code>; its pixels are stored separately under the same id.</p>

  <h2 id="backup">The backup file</h2>
  <p><code>cultifolio-YYYY-MM-DD.cultifolio.zip</code>, an ordinary zip:</p>
<pre><code>{`manifest.json        format, version, when, device, counts (photos = photographs actually in the file), numbering scheme,
                     photosMissing: ids of photo records whose pixels were not on the exporting device
changes.json         the whole change log, as above
photos/<id>.jpg      full-size JPEG, long edge 1600 px
photos/<id>.t.jpg    320 px thumbnail
plants.csv           one row per plant, for a spreadsheet (not for import)`}</code></pre>
  <p>Restoring merges by the log rule, so restoring an old file over a newer collection loses nothing and restoring twice changes nothing. The older changes-only JSON export (<code>{`{ "format": "cultifolio-changes", "changes": [...] }`}</code>) is still accepted, as is a v2 Herbarium backup.</p>

  <h2 id="sync">Sync on the wire</h2>
  <p>One vault key per person: 30 symbols from an alphabet without I, L, O, U, 0 or 1, in six groups of five. From it, HKDF-SHA-256 with salt <code>cultifolio-vault-v1</code> derives an AES-256-GCM key (info <code>enc</code>), a 256-bit auth token (info <code>auth</code>, sent hex as a bearer) and an HMAC-SHA-256 key for naming batches (info <code>name</code>). The vault id is the first 26 symbols of SHA-256 of <code>id:</code> + token, in the same alphabet. The server stores SHA-256 of <code>token:</code> + token and compares; at creation, the one moment it sees the token itself, it also checks that the id is the one that token derives, so a vault cannot be made under a name its key would not produce.</p>
  <p>A sealed blob is one version byte (1), a 12-byte IV, then AES-GCM ciphertext with associated data <code>vaultId|kind</code>, where kind is <code>log</code> or <code>photo</code>, so a blob cannot be replayed into another vault or as another kind; a photo's data also carries its id (<code>vaultId|photo|photoId</code>), so it cannot be handed out under another photo's id. A log batch decrypts to <code>{`{ "v": 1, "device": "...", "changes": [...] }`}</code> and is stored at <code>vault/&lt;id&gt;/log/&lt;hour&gt;-0000-&lt;device&gt;-&lt;fingerprint&gt;.bin</code> where <code>&lt;hour&gt;</code> is the hour (in ms) of the batch's last change, <code>&lt;device&gt;</code> the pushing device and <code>&lt;fingerprint&gt;</code> the first twelve hex digits of HMAC-SHA-256, under the vault's naming key, of the changes as JSON before sealing. Every seal uses a fresh IV, so the same batch pushed twice is different bytes under the same name; the pushing device sends the full fingerprint (<code>X-Batch-Plain</code>) and its id (<code>X-Device</code>), and when both match what the server kept with the first copy it answers that the batch is already there and stores nothing. Different bytes under a held name without that match are refused (409), so a name never stands for two contents. The fingerprint is keyed so that the server holds nothing it could test a guessed plaintext against; earlier builds named batches by the last change's full HLC and an unkeyed SHA-256, and those names remain valid. A batch the device cannot open or validate is set aside by name and reported, and does not stop the ones behind it; a batch that cannot be stored on the device (a full phone) is not set aside: the sync stops with an error and fetches it again next time. A change stamped more than five minutes ahead of the receiving device's clock is stored but held out of the merge until that clock reaches it, and the sync page says how many are waiting; otherwise one fast phone would win every field it touched on every device. Batches are handed out in the order they <em>arrived</em> at the server, not in key order: a device that edited offline and uploads after another device has already pulled past that time must still be found, so a client asks for everything since a server arrival time, re-reads a minute of overlap, and skips batches it already holds; within one sync it pages on the pair (arrival, key), so many batches arriving in the same second cannot repeat. The changes inside carry the HLCs that settle merges; arrival order only decides discovery. A photo decrypts to a 4-byte big-endian length, the full JPEG, then the thumbnail, at <code>vault/&lt;id&gt;/photo/&lt;id&gt;.bin</code>. Nothing is rewritten or deleted.</p>
  <p>The endpoints: <code>POST /api/sync/vault</code> {`{ id, token, create }`}; <code>GET /api/sync/log?vault=&amp;since=&lt;ms&gt;</code> (returns <code>{`{ batches: [{ key, at }], more, next?: { at, key } }`}</code>; the next page is <code>&amp;after=&lt;at&gt;:&lt;key&gt;</code>); <code>POST /api/sync/log?vault=</code> with headers <code>X-Batch</code>, <code>X-Batch-Plain</code>, <code>X-Device</code>; <code>GET /api/sync/log/&lt;hlc&gt;-&lt;hash&gt;?vault=</code>; <code>PUT|GET|HEAD /api/sync/photo/&lt;id&gt;?vault=</code>. All but creation take <code>Authorization: Bearer &lt;token&gt;</code>. A body larger than the limit is 413; a vault with no room left (2 GB) is 507 with <code>{`{ error: "vault full", bytes, limit }`}</code>, and the device stops sending and says so rather than splitting the batch. Every refusal is plain JSON with an <code>error</code> the device can show. One address is bounded: 20 new vaults and 3 GB stored per day, 600 requests per ten minutes to open, list and push and 3,000 to fetch or store single batches and photographs; past any of these the answer is 429 with <code>Retry-After</code> in seconds, and the device simply tries again later. The byte counts live in KV, kept per object; a listing of the vault puts them right on every open and once a day, so two uploads in the same instant can overshoot the allowance by at most one object until then.</p>
  <p>What the server can see. It holds a vault id, a hash of the token, and sealed blobs, and it cannot open any of them. But the blob names, sizes and arrival times are in the clear: a batch is named by the hour and device id of its last change, a photograph by the time and device id of its creation, and a sealed photograph is a few bytes larger than its JPEG. So the operator can count the devices in a vault, see to the hour when each one made changes and to the second when it synced, count the batches (roughly, how often changes are made) and the photographs, and read their sizes. This is not zero-knowledge in the strict sense: the pattern of activity is visible, its content is not. Nothing about the plants themselves (names, notes, places, dates, the number of plants) is visible, and nothing is ever written into a vault by anyone but its devices.</p>

  <h2 id="dossier">A species dossier</h2>
  <p>Each species page is rendered from one JSON document, served at <code>/api/dossier/&lt;gbifKey&gt;</code>: name and classification, native range as TDWG level-3 codes, open occurrence points with licence tags, the map marker and how it was placed, the climate envelope (median year, 10th and 90th percentile years, the cells and records it rests on, the typical cell) with its sources, extremes, photographs with author and licence, the summary with its licence, literature, links, and an <code>upstream</code> block recording for every source whether it answered, refused, or was carried from an earlier build. The corpus is built from public data under CC0, CC BY and CC BY-SA and will be published as a dataset.</p>
</article>

<style>
  .prose { max-width: 720px; font-size: 15px; line-height: 1.6; color: var(--ink); font-family: var(--ui); }
  .prose h2 { font-family: var(--serif); font-size: 22px; margin: 28px 0 8px; }
  .prose p { margin: 0 0 12px; }
  .prose pre { background: var(--sunk); border-radius: 9px; padding: 12px 14px; overflow-x: auto; font-size: 12.5px; line-height: 1.5; margin: 0 0 12px; }
  .prose code { font-family: var(--mono); font-size: 12.5px; }
  .prose p code { background: var(--sunk); padding: 1px 5px; border-radius: 4px; }
  .topseg { margin: 14px 0 6px; }
</style>
